In [9]:
import numpy as np
import matplotlib.pyplot as plt
import os 
import os.path as osp

In [10]:
grad_from_E_path = "/data/ruihan/projects/PhysDreamer/physdreamer/warp_mpm/logs/20250411/stress_tensor_from_E.npz"
grad_from_stress_path = "/data/ruihan/projects/PhysDreamer/physdreamer/warp_mpm/logs/20250411/stress_tensor.npz"

stress_grad_from_E = np.load(grad_from_E_path)["stress_grad"]
stress_grad_from_stress = np.load(grad_from_stress_path)["stress_grad"]

stress_from_E = np.load(grad_from_E_path)["stress"]
stress_from_stress = np.load(grad_from_stress_path)["stress"]

print(np.allclose(stress_grad_from_E, stress_grad_from_stress), np.allclose(stress_from_E, stress_from_stress))

True False


In [11]:
print(stress_from_E)


[[[ 6.12032288e-03  7.92535912e-21 -6.79492322e-19]
  [ 7.92535912e-21  6.12032271e-03  1.18623679e-35]
  [-6.79492322e-19  1.18623679e-35  1.70803542e-10]]

 [[ 6.12032288e-03  7.92535912e-21 -6.79492322e-19]
  [ 7.92535912e-21  6.12032271e-03  1.18623679e-35]
  [-6.79492322e-19  1.18623679e-35  1.70803542e-10]]

 [[ 6.12032288e-03  7.92535912e-21 -6.79492322e-19]
  [ 7.92535912e-21  6.12032271e-03  1.18623679e-35]
  [-6.79492322e-19  1.18623679e-35  1.70803542e-10]]

 [[ 6.12032288e-03  7.92535912e-21 -6.79492322e-19]
  [ 7.92535912e-21  6.12032271e-03  1.18623679e-35]
  [-6.79492322e-19  1.18623679e-35  1.70803542e-10]]

 [[ 6.12032288e-03  7.92535912e-21 -6.79492322e-19]
  [ 7.92535912e-21  6.12032271e-03  1.18623679e-35]
  [-6.79492322e-19  1.18623679e-35  1.70803542e-10]]

 [[ 6.12032288e-03  7.92535912e-21 -6.79492322e-19]
  [ 7.92535912e-21  6.12032271e-03  1.18623679e-35]
  [-6.79492322e-19  1.18623679e-35  1.70803542e-10]]

 [[ 6.12032288e-03  7.92535912e-21 -6.79492322e-19]


In [8]:
print(stress_from_stress)

[[[ 0.04585001  0.00675951 -0.01730125]
  [ 0.00675951  0.04585001 -0.01194403]
  [-0.01730125 -0.01194403  0.04585001]]

 [[ 0.04584978  0.00675947 -0.01730116]
  [ 0.00675947  0.04584978 -0.01194397]
  [-0.01730116 -0.01194397  0.04584978]]

 [[ 0.04584976  0.00675947 -0.01730115]
  [ 0.00675947  0.04584976 -0.01194397]
  [-0.01730115 -0.01194397  0.04584976]]

 [[ 0.04584988  0.00675949 -0.0173012 ]
  [ 0.00675949  0.04584988 -0.011944  ]
  [-0.0173012  -0.011944    0.04584988]]

 [[ 0.04584976  0.00675947 -0.01730115]
  [ 0.00675947  0.04584976 -0.01194396]
  [-0.01730115 -0.01194396  0.04584976]]

 [[ 0.04584985  0.00675949 -0.01730118]
  [ 0.00675949  0.04584985 -0.01194399]
  [-0.01730118 -0.01194399  0.04584985]]

 [[ 0.04584984  0.00675948 -0.01730118]
  [ 0.00675948  0.04584984 -0.01194399]
  [-0.01730118 -0.01194399  0.04584984]]

 [[ 0.0458498   0.00675948 -0.01730117]
  [ 0.00675948  0.0458498  -0.01194398]
  [-0.01730117 -0.01194398  0.0458498 ]]

 [[ 0.04584984  0.006759